### ISSUE TITLE
How to assign opacity?

### ISSUE THREAD

**Issue by MrMcyeet** [iseahound/TextRender#10]
Using this here 

```
tr.Render("Off", {x: A_ScreenWidth-Width_Offset, y: A_ScreenHeight-Height_Offset, color: "Red"})
```

![image](https://user-images.githubusercontent.com/68966344/156008944-894ebb47-0310-4e5e-a5c4-4eeab57c94f2.png)

It displays correctly what I want it to, but is there a way to change the opacity of the red? I tried using cRRGGBBAA format, but to no avail.

**Comment by iseahound** [comment]
#include TextRender (for v1).ahk
    tr := TextRender()
    tr.Render("Off", {x: A_ScreenWidth-Width_Offset, y: A_ScreenHeight-Height_Offset, color: 0xAAFF0000})

Make sure that you quote strings in objects. `{color: "#AAFF0000"})` would work too.

**Comment by MrMcyeet** [comment]
Sure
