### ISSUE TITLE
TextRender GUI is unavailable

### ISSUE THREAD

**Issue by Fortress937** [iseahound/TextRender#13]
![image](https://user-images.githubusercontent.com/119410273/211237541-7f385461-f889-4619-99d8-a1bfb08ce023.png)

this problem keep persisting even though i use Autohotkey version 2

**Comment by iseahound** [comment]
It's not implemented at the moment due to lack of users

**Comment by Fortress937** [comment]
ooh, i see. hope that can be implemented

**Comment by iseahound** [comment]
So to clarify, the TextRender GUI would be an application that generates TextRender code. Currently, you can use TextRender based off the code examples I've given.  

If you'd like some examples, you can run the ones in the test folder. 
If you need some idea of how to use TextRender, see the Quick Start here https://github.com/iseahound/TextRender/wiki/Quick-Start#textrender-tutorial

**Comment by iseahound** [comment]
Likely won't be implemented as I don't like designing GUIs.
