### ISSUE TITLE
SetThreadDpiAwarenessContext in win7

### ISSUE THREAD

**Issue by sxzxs** [iseahound/TextRender#14]
CoSetThreadDpiAwarenessContext function is in Windows 8.1 or higher version of the operating system, the introduction of doesn't support Windows 7.

**Comment by iseahound** [comment]
It may take some time for me to do some Windows 7 testing, but I'll add a quick fix. See if ca42005ef148410f6580790beb54c5cb5a79cb21 works for you.

**Comment by sxzxs** [comment]
Thanks to fix！
