### ISSUE TITLE
Thought you should know you're fantastic!

### ISSUE THREAD

**Issue by D-o-u-g-K** [iseahound/TextRender#15]
I created a github account just to tell you that. I  looked for a way to message you, perhaps I need a certain amount of activity to unlock that. 

Anyways, I've seen countless posts/replies of your's around the autohotkey forums (reddit aswell I believe). You deserve many thanks before you even take into account the fantastic projects you've published. Vis2 is still the only tesseract ahk library, to my knowledge, that doesn't require using an executable w/gui or running commands through a command line exe. Textrender is obviously great, which I'm also using for business applications (no money for me, family business, even though the license would allow). A small but most recent example, I needed a way to alert technicians if a packaging robot had orders waiting to pick up, but didn't want the screen occluded by a listview of sql records. So now there is a small circle on the screen, that they can move. It turns green when robots empty, orange when orders to pick up. If they click or hit CTRL-M, the individual orders show up for them to browse. Not the coolest one, but way better than message boxes stealing focus! 

Anyways, I saw your discussion reply where you said ahk v2 gui wasn't implemented yet due to lack of library users. I'm still using v1 anyways, for now, but thought you might need reminded you're talented and appreciated!

Thanks for your efforts

**Comment by iseahound** [comment]
Cheers! And a Happy New Year to you too
