### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by H5820121** [iseahound/TextRender#17]
@iseahound 
Thanks for the amazing and useful script!
1. I want to display the Inf Icon (\System32\shell32.dll|icon222) next to the text, how do I do it?
2. Is it possible to display the text next to the mouse cursor (I want to use this as a tooltip)?
AHK V2
Thank you!

**Comment by iseahound** [comment]
2. No. See btt BeautifulToolTip
1. idk. Maybe use ImagePut

**Comment by H5820121** [comment]
@iseahound 
Thank you for replying!
It would be very helpful for me if you could please give me an example of how by ImagePut I can display Inf Icon (\System32\shell32.dll|icon222).
Thank you!

**Comment by iseahound** [comment]
https://www.autohotkey.com/boards/viewtopic.php?p=584634#p584634

**Comment by H5820121** [comment]
> 2. No. See btt BeautifulToolTip
> 
> 1. idk. Maybe use ImagePut

Thanks, but unfortunately BeautifulToolTip is AHK V1, I need V2 so I can include it in my V2 scripts.
