### ISSUE TITLE
Is it normal for Flush() to not display any content?

### ISSUE THREAD

**Issue by telppa** [iseahound/TextRender#3]
```
tr := new TextRender
tr.draw("hello world!`n我爱吃苹果哈哈哈")
tr.Flush()

Sleep, 3000
ExitApp

#Include TextRender.ahk
```

**Comment by iseahound** [comment]
Yes, the normal operation of a flush() function is to reset the internals. It clears the graphics, but does not update the screen. When you call Clear(), it calls Flush() to clear the internal graphics, then UpdateLayeredWindow to clear the screen. I'm sorry the documentation is bad.

**Comment by telppa** [comment]
no, the documentation is good. I learned a lot.

I'm trying to learn more about textrender so I can create some examples to help others use and understand it.

**Comment by iseahound** [comment]
Here is an example of using Flush() to replace Render()

    #include TextRender.ahk
    #Persistent

        tr := TextRender()
        tr.Draw("Quiz explained for TV show by Mick Jagger.")
        tr.Save("1.png")
        tr.Flush() ; I don't want to display on screen, only create files.

        tr.Draw("Back in June we delivered oxygen equipment of the same size.")
        tr.Save("2.png")
        tr.Flush()

    Esc:: ExitApp

**Comment by telppa** [comment]
thank you, i understand this.

I've created a new example that might help users understand tr.Flush() more graphically.

```
#include TextRender.ahk
#Persistent

    tr := TextRender()

    tr.Draw("Back in June we delivered oxygen equipment of the same size.")
    tr.Save("1.png")  ; I don't want to display on screen, only create files.
    
    tr.Draw("Quiz explained for TV show by Mick Jagger.")
    tr.Save("2.png")
    
    tr.Flush()        ; clear the graphics. you can see the difference between 2.png and 3.png
    tr.Draw("Quiz explained for TV show by Mick Jagger.")
    tr.Save("3.png")

Esc:: ExitApp

```

**Comment by iseahound** [comment]
I have no place to share code with you but if you are making examples here's one of mine:

    #include TextRender (for v1).ahk
    SetBatchLines -1

    button1 := TextRender("Width", {y:"42vh", r:5, c:"DeepSkyBlue"})
    button2 := TextRender("Height", {x:"42vw", r:5, c:"DarkOrange"})
    button3 := TextRender("Exit", {x:"90vw", y:"90vh", r:5, c:"Red"})

    button1.OnEvent("LeftMouseDown", Func("start_width"))
    button2.OnEvent("LeftMouseDown", Func("start_height"))
    button3.OnEvent("LeftMouseDown", Func("ExitApp"))

    ExitApp() {
        ExitApp
    }

    start_width() {
        dpi := DllCall("SetThreadDpiAwarenessContext", "ptr", -4, "ptr")
        sx := DllCall("GetSystemMetrics", "int", 76, "int")
        sy := DllCall("GetSystemMetrics", "int", 77, "int")
        sw := DllCall("GetSystemMetrics", "int", 78, "int")
        sh := DllCall("GetSystemMetrics", "int", 79, "int")
        DllCall("SetThreadDpiAwarenessContext", "ptr", dpi, "ptr")

        x := sx
        tr := TextRender()

        DllCall("QueryPerformanceFrequency", "int64*", frequency:=0)
        DllCall("QueryPerformanceCounter", "int64*", start:=0)
        while (x < sx + sw) {
            tr.render(f := A_Index, {a:2, x:x, m:0, y:"Top"}, "s:108")
            x++
        }
        DllCall("QueryPerformanceCounter", "int64*", end:=0)

        fps := (end - start) / frequency
        fps := f / fps
        TextRender(fps " fps", "t:3000 y:25vh c:RoyalBlue")
    }

    start_height() {
        dpi := DllCall("SetThreadDpiAwarenessContext", "ptr", -4, "ptr")
        sx := DllCall("GetSystemMetrics", "int", 76, "int")
        sy := DllCall("GetSystemMetrics", "int", 77, "int")
        sw := DllCall("GetSystemMetrics", "int", 78, "int")
        sh := DllCall("GetSystemMetrics", "int", 79, "int")
        DllCall("SetThreadDpiAwarenessContext", "ptr", dpi, "ptr")

        y := sy
        tr := TextRender()

        DllCall("QueryPerformanceFrequency", "int64*", frequency:=0)
        DllCall("QueryPerformanceCounter", "int64*", start:=0)
        while (y < sy + sh) {
            tr.render(f := A_Index, {a:4, x:"left", m:0, y:y}, "s:108")
            y++
        }
        DllCall("QueryPerformanceCounter", "int64*", end:=0)

        fps := (end - start) / frequency
        fps := f / fps
        TextRender(fps " fps", "t:3000 x:25vw c:RoyalBlue")
    }

    Esc:: ExitApp
