### ISSUE TITLE
i don't understand tr.Sleep()

### ISSUE THREAD

**Issue by telppa** [iseahound/TextRender#4]
when i click the message box. it shows nothing.
it seems to be the same as tr.clear()

```
tr := new TextRender
tr.draw("hello world!`n我爱吃苹果哈哈哈")
tr.render()
MsgBox
tr.Sleep(1000)

Sleep, 3000
ExitApp

#Include TextRender.ahk
```

**Comment by iseahound** [comment]
The new version fixes Sleep(). Maybe it should be called Wait()?

* If you give it a number it will clear the render and wait that amount of time before returning.
* If you specified a time to show in the last call it will wait that amount of time.
* Also it is used for the following code style

#include TextRender (for v1).ahk

    tr := TextRender()

    tr
        .Render("Apple", "t: 1000 c:Random")
        .Sleep()
        .Render("Banana", "t: 1000 c:Random")
        .Sleep()
        .Render("Cherry", "t: 1000 c:Random")
        .Sleep()
        .Render("Dragonfruit", "t: 1000 c:Random")
        .Sleep()

    tr
        .Render("a", "t: 1000 c:Random")
        .Sleep(1000)
        .Render("b", "t: 1000 c:Random")
        .Sleep(1000)
        .Render("c", "t: 1000 c:Random")
        .Sleep(1000)
        .Render("d", "t: 1000 c:Random")

If you have any suggestions, please let me know.

**Comment by telppa** [comment]
I agree with the change to wait() .

I think it would be easier for users to understand what it does if put these examples in the sleep() 's wiki.
