### ISSUE TITLE
color:Delete or color:Erase seems wrong.

### ISSUE THREAD

**Issue by telppa** [iseahound/TextRender#8]
```
tr := new TextRender
tr.draw("hello world!`n我爱吃苹果哈哈哈","c:red","color:Delete")
tr.render()

Sleep, 3000
ExitApp

#Include TextRender.ahk
```

![1](https://user-images.githubusercontent.com/68984587/150066967-12210081-8183-440a-bef8-e83541bcddbd.png)

**Comment by iseahound** [comment]
I was never able to fix this bug. It used to work in an old version, but I suspect Microsoft changed it and I haven't gotten it to work since.

I checked the old versions of TextRender, and it likely only works on old versions of Windows only.
