### ISSUE TITLE
Overlay does re-launch when in new Window Context

### ISSUE THREAD

**Issue by zDEFz** [iseahound/TextRender#9]
**Precondition**
Use with Programs that require fullscreen.
Happened with several VNC clients, an openGL game. Never happened when only staying in Windowed mode.
Does also happen with AutoHotKey's standalone ToolTips.

**How to reproduce (sometimes)**
1. Display some text via ``tr := TextRender("Sample text", "time:1000")``  and then alt tabbing to a application that runs in exclusive fullscreen mode.
2. Wait some time, alt tab again to the fullscreen application
**Effect**
The sample text is shown each time I enter the fullscreen application for the specified timeframe

**Question** Does this have todo with framebuffer perhaps? Does the text really gets cleared up?
It's strange that it 'reloads' every time, if it happens, after an context change.

Hardware: Lenovo T490 with intel iGPU
Windows 10, 

**Additional info**
Sometimes the displayed Text gets "stuck" even without being in fullscreen mode.

**Textrender info**
; Date:      2021-05-22
; Version:   v1.06

**Comment by iseahound** [comment]
I believe this is a bug. Your full screen window application sends the `WM_DISPLAYCHANGE` window message to all apps, indicating that the screen resolution has changed. When TextRender receives this method, it attempts to reload all instances to be compatible with the new screen width and height. 

However, it is missing a check for the "time" attribute.

**Comment by zDEFz** [comment]
> I believe this is a bug. Your full screen window application sends the `WM_DISPLAYCHANGE` window message to all apps, indicating that the screen resolution has changed. When TextRender receives this message, it attempts to reload all instances to be compatible with the new screen width and height.
> 
> However, it is missing a check for the "time" attribute.
> 
> > Sometimes the displayed Text gets "stuck" even without being in fullscreen mode.
> 
> What is stuck?

In some windows, the TextRender Window persists indefinitely and doesn't get cleared out. The last occurence where I saw that was the TurboVNC viewer.

**Comment by iseahound** [comment]
#include TextRender.ahk

    tr := TextRender("Sample text", "time:1000")
    Sleep 2000
    ChangeDisplaySettings(32, 1280,  720, 60)
    Sleep 2000
    ChangeDisplaySettings(32, 1920, 1080, 60)

    Esc:: ExitApp

    ChangeDisplaySettings( cD, sW, sH, rR ) {
        VarSetCapacity(dM,156,0), NumPut(156,2,&dM,36)
        DllCall( "EnumDisplaySettingsA", UInt,0, UInt,-1, UInt,&dM ), NumPut(0x5c0000,dM,40)
        NumPut(cD,dM,104),  NumPut(sW,dM,108),  NumPut(sH,dM,112),  NumPut(rR,dM,120)
        Return DllCall( "ChangeDisplaySettingsA", UInt,&dM, UInt,0 )
    }

I can reproduce only part of the behavior you describe. I'm not sure about things getting stuck, so I'll work on fixing what I can first.

**Comment by iseahound** [comment]
I've uploaded a version that (hopefully) solves the problem.

    #include TextRender (for v1).ahk

    time := 0
    SetTimer timer, 1000
    tr := TextRender("Sample text", "time:5000")
    Sleep 3000
    ChangeDisplaySettings(32, 1280,  720, 60)
    Sleep 3000
    ChangeDisplaySettings(32, 1920, 1080, 60)

    ExitApp

    timer:
        Tooltip % time += 1000
    return

    ChangeDisplaySettings( cD, sW, sH, rR ) {
        VarSetCapacity(dM,156,0), NumPut(156,2,&dM,36)
        DllCall( "EnumDisplaySettingsA", UInt,0, UInt,-1, UInt,&dM ), NumPut(0x5c0000,dM,40)
        NumPut(cD,dM,104),  NumPut(sW,dM,108),  NumPut(sH,dM,112),  NumPut(rR,dM,120)
        Return DllCall( "ChangeDisplaySettingsA", UInt,&dM, UInt,0 )
    }

**Comment by zDEFz** [comment]
Fixed. Thank you so much!

**Comment by zDEFz** [comment]
Re-open. Had updated the script. But for some reason still happens, but no more gets 'stuck'. Reproduction

https://user-images.githubusercontent.com/24463722/150690211-ac95b793-14d2-4324-88bb-94164cb402ca.mp4

**Comment by iseahound** [comment]
How did you switch out of mac mini? Alt-Tab? Or another hotkey?

**Comment by iseahound** [comment]
I'm also confused by your script:

* There is a comma in `#include` which I've never seen before
* There are also brackets `{}` around the hotkeys which is v2 syntax. 
* tr.clear() is past the auto-execute section and will never run.
* You don't need to assign `tr := TextRender()` if you specify a time parameter. That's better for creating anonymous TextRender instances and will probably solve your problem.

**Comment by zDEFz** [comment]
> I'm also confused by your script:
> 
> * There is a comma in `#include` which I've never seen before
> * There should not be brackets `{}` around the hotkeys which is v2 syntax.
> * tr.clear() is past the auto-execute section and will never run.
> * You don't need to assign `tr := TextRender()` if you specify a time parameter. That's better for creating anonymous TextRender instances and will probably solve your problem. Try `TextRender("Switching to mac mini", "t:1000")`.
> 
> It looks like you're using AutoHotkey v2.

1. I use a "," in the folder itself, thus it is also in the path.
2. Yes, I'm using AHK v2.
3. A remnant, forgot to remove that.
4. Yea, I try that. Thanks.

**Comment by zDEFz** [comment]
> How did you switch out of mac mini? Alt-Tab? Or another hotkey?

Alt+Tab

**Comment by iseahound** [comment]
Side Question: Do you need this script to work on AutoHotkey v2?

**Comment by zDEFz** [comment]
> Side Question: Do you need this script to work on AutoHotkey v2?

No. Just an early-adopter. If the issue persists on the version v2, I will test with the most recent stable version of Autohotkey.

**Comment by iseahound** [comment]
The latest commit 6dec377fd1e8dd8bab42c381e5dfa4cb3471a0f0 should fix the problem you described. Let me know if there are any further issues.

**Comment by iseahound** [comment]
The latest commit 9a42da81401e52c2da4202b3a0b0aaa817595cec works on my end. Please let me know if it is working properly.

**Comment by zDEFz** [comment]
> The latest commit [9a42da8](https://github.com/iseahound/TextRender/commit/9a42da81401e52c2da4202b3a0b0aaa817595cec) works on my end. Please let me know if it is working properly.

I could not find a reproduction within the last days. If it happens again, I let you know.
